from django.urls import path
from . import views

urlpatterns = [
    path("search/", views.part_search, name="part_search"),
    path("vehicles/", views.vehicle_catalog, name="vehicle_catalog"),
    path("pos/", views.pos_console, name="pos_console"),
    path("transfers/", views.transfer_list, name="transfer_list"),
    path("transfers/new/", views.transfer_create, name="transfer_create"),
    path("transfers/create/<int:stock_id>/", views.transfer_create_from_stock, name="transfer_create_from_stock"),
    path("transfers/approvals/", views.transfer_approvals, name="transfer_approvals"),
    path("transfers/<int:transfer_id>/approve/", views.transfer_approve, name="transfer_approve"),
    path("transfers/<int:transfer_id>/reject/", views.transfer_reject, name="transfer_reject"),
    path("transfers/driver/", views.transfer_driver_tasks, name="transfer_driver_tasks"),
    path("transfers/<int:transfer_id>/pickup/", views.transfer_mark_picked_up, name="transfer_mark_picked_up"),
    path("transfers/<int:transfer_id>/delivered/", views.transfer_mark_delivered, name="transfer_mark_delivered"),
    path("transfers/receive/", views.transfer_receive_list, name="transfer_receive_list"),
    path("transfers/<int:transfer_id>/confirm-receive/", views.transfer_confirm_receive, name="transfer_confirm_receive"),
    path("add-to-cart/<int:stock_id>/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart_view, name="cart_view"),
    path("cart/update/<int:stock_id>/", views.update_cart_item, name="update_cart_item"),
    path("cart/clear/", views.clear_cart, name="clear_cart"),
    path("active-branch/", views.set_active_branch, name="set_active_branch"),
    path("checkout/", views.finalize_order, name="finalize_order"),
    path("receipt/<str:order_id>/", views.receipt_view, name="receipt_view"),
    path("orders/", views.order_list, name="order_list"),
    path("audit/", views.audit_log_list, name="audit_log_list"),
    path("tickets/", views.ticket_list, name="ticket_list"),
    path("tickets/new/", views.ticket_create, name="ticket_create"),
    path("tickets/<int:ticket_id>/", views.ticket_detail, name="ticket_detail"),
    path("scan/", views.scan_dispatch, name="scan_dispatch"),
    path("scan/resolve/", views.scan_resolve, name="scan_resolve"),
    path("stock/scan/apply/", views.stock_scan_apply, name="stock_scan_apply"),
    path("scanner/", views.scanner_view, name="scanner_view"),
    path("sell/<int:stock_id>/", views.sell_part, name="sell_part"),
    path("reports/", views.reports_dashboard, name="reports_dashboard"),
    path("assistant/", views.analytics_assistant, name="analytics_assistant"),
    path("chat/", views.analytics_assistant, name="chat_assistant"),
    path("history/", views.sales_history, name="sales_history"),
    path("history/refund/<int:sale_id>/", views.refund_sale, name="refund_sale"),
    path("history/export/", views.export_sales_csv, name="export_sales_csv"),
    path("low-stock/", views.low_stock_list, name="low_stock_list"),
    path("low-stock/export/", views.export_low_stock_csv, name="export_low_stock_csv"),
    path("locations/", views.location_list, name="location_list"),
    path("stock-locations/", views.stock_locations_view, name="stock_locations_view"),
    path("stock-by-location/", views.stock_locations_view, name="stock_by_location"),
]
