# Generated by Django 5.2.10 on 2026-01-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stock_location_in_warehouse_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
