# Generated by Django 5.2.10 on 2026-02-22 08:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_profiles_and_order_branch(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Branch = apps.get_model("inventory", "Branch")
    UserProfile = apps.get_model("inventory", "UserProfile")
    Order = apps.get_model("inventory", "Order")
    Sale = apps.get_model("inventory", "Sale")

    default_branch = Branch.objects.order_by("id").first()
    for user in User.objects.all():
        role = "admin" if user.is_superuser else "cashier"
        profile, created = UserProfile.objects.get_or_create(
            user=user,
            defaults={"role": role},
        )
        if not created and user.is_superuser and profile.role != "admin":
            profile.role = "admin"
            profile.save(update_fields=["role"])

        if default_branch and not user.is_superuser and not profile.branch_id:
            profile.branch = default_branch
            profile.save(update_fields=["branch"])

    for order in Order.objects.filter(branch__isnull=True):
        first_branch_id = (
            Sale.objects.filter(order_id=order.id)
            .exclude(branch_id__isnull=True)
            .order_by("id")
            .values_list("branch_id", flat=True)
            .first()
        )
        if first_branch_id:
            order.branch_id = first_branch_id
            order.save(update_fields=["branch"])


def reverse_seed_profiles_and_order_branch(apps, schema_editor):
    # Keep migration reversible without destructive data deletion.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_customer_order_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier')], default='cashier', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='part',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='part',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cost_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='inventory_o_created_60ea1c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'created_at'], name='inventory_o_branch__8a2dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date_sold'], name='inventory_s_date_so_47b59f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'date_sold'], name='inventory_s_branch__50a6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['branch', 'quantity'], name='inventory_s_branch__10fe18_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0)), name='order_vat_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='order_discount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='order_grand_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('price_at_sale__gte', 0)), name='sale_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('cost_at_sale__gte', 0)), name='sale_cost_gte_0'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Default branch scope for non-manager users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(seed_profiles_and_order_branch, reverse_seed_profiles_and_order_branch),
    ]
