# Generated by Django 5.2.10 on 2026-02-22 09:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_userprofile_order_branch_alter_customer_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('received', 'Received')], default='requested', max_length=20)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('destination_branch', models.ForeignKey(help_text='Branch that requested stock (Branch A).', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer_requests', to='inventory.branch')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_driving', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='inventory.part')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_received', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_created', to=settings.AUTH_USER_MODEL)),
                ('source_branch', models.ForeignKey(help_text='Branch that will send stock (Branch B).', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfer_requests', to='inventory.branch')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='inventory_t_status_4a5024_idx'), models.Index(fields=['source_branch', 'status'], name='inventory_t_source__6dc20b_idx'), models.Index(fields=['destination_branch', 'status'], name='inventory_t_destina_94cd5e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_qty_gt_0'), models.CheckConstraint(condition=models.Q(('source_branch__isnull', False), ('destination_branch__isnull', False)), name='transfer_source_dest_not_null'), models.CheckConstraint(condition=models.Q(('source_branch', models.F('destination_branch')), _negated=True), name='transfer_source_ne_destination'), models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='transfer_reserved_qty_gte_0'), models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='transfer_reserved_qty_lte_qty')],
            },
        ),
    ]
