# Generated by Django 5.2.10 on 2026-02-22 10:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_transferrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(default='SYSTEM', max_length=150)),
                ('actor_employee_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory.branch')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='inventory_a_action_92f4bf_idx'), models.Index(fields=['actor_employee_id', 'timestamp'], name='inventory_a_actor_e_14b791_idx'), models.Index(fields=['branch', 'timestamp'], name='inventory_a_branch__a42e8d_idx')],
            },
        ),
    ]
