# Generated by Django 5.2.10 on 2026-02-22 10:33

from django.conf import settings
from django.db import migrations, models


def _next_unique_employee_id(base: str, seen: set[str]) -> str:
    candidate = base[:50]
    suffix = 1
    while candidate in seen:
        token = f"-{suffix}"
        candidate = f"{base[:50 - len(token)]}{token}"
        suffix += 1
    return candidate


def populate_employee_ids(apps, schema_editor):
    UserProfile = apps.get_model("inventory", "UserProfile")

    seen = set()
    profiles = UserProfile.objects.all().order_by("id")
    for profile in profiles:
        employee_id = (profile.employee_id or "").strip()
        if employee_id and employee_id not in seen:
            if employee_id != profile.employee_id:
                profile.employee_id = employee_id
                profile.save(update_fields=["employee_id"])
            seen.add(employee_id)
            continue

        base = f"AUTO-{int(profile.user_id or profile.id):05d}"
        profile.employee_id = _next_unique_employee_id(base, seen)
        profile.save(update_fields=["employee_id"])
        seen.add(profile.employee_id)


def reverse_populate_employee_ids(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_userprofile_employee_id_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(populate_employee_ids, reverse_populate_employee_ids),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('employee_id', ''), _negated=True), name='userprofile_employee_id_not_blank'),
        ),
    ]
