# Generated by Django 5.2.10 on 2026-02-22 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_userprofile_employee_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.CharField(default='system', max_length=255),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['reason', 'timestamp'], name='inventory_a_reason_3fb0a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='auditlog_reason_not_blank'),
        ),
    ]
