# Generated by Django 5.2.10 on 2026-02-22 21:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_stock_locations(apps, schema_editor):
    Location = apps.get_model('inventory', 'Location')
    Stock = apps.get_model('inventory', 'Stock')
    StockLocation = apps.get_model('inventory', 'StockLocation')

    for stock in Stock.objects.filter(quantity__gt=0).iterator():
        location, _ = Location.objects.get_or_create(
            branch_id=stock.branch_id,
            code='UNASSIGNED',
            defaults={
                'name_ar': 'غير محدد',
                'name_en': 'Unassigned',
            },
        )
        stock_location, _ = StockLocation.objects.get_or_create(
            part_id=stock.part_id,
            branch_id=stock.branch_id,
            location_id=location.id,
            defaults={'quantity': 0},
        )
        stock_location.quantity += stock.quantity
        stock_location.save(update_fields=['quantity'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auditlog_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.branch')),
            ],
            options={
                'ordering': ['branch__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='inventory.branch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='inventory.location')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='inventory.part')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('action', models.CharField(max_length=40)),
                ('reason', models.CharField(default='system', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.branch')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='inventory.location')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.part')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='inventory.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['branch', 'code'], name='inventory_l_branch__d6e485_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='location_branch_code_unique'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['branch', 'part'], name='inventory_s_branch__5e9157_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['location', 'part'], name='inventory_s_locatio_1b5dcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(fields=('part', 'branch', 'location'), name='stocklocation_part_branch_location_unique'),
        ),
        migrations.RunPython(seed_stock_locations, noop_reverse),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch', 'created_at'], name='inventory_s_branch__377a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['part', 'created_at'], name='inventory_s_part_id_9aaba5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['action', 'created_at'], name='inventory_s_action_ae5589_idx'),
        ),
    ]
