# Generated by Django 5.2.10 on 2026-02-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_location_stocklocation_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
