# Generated by Django 5.2.10 on 2026-02-24 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='tickets/screenshots/'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['branch', 'status', 'created_at'], name='inventory_t_branch__40afb3_idx'),
        ),
    ]
