# Generated by Django 5.2.10 on 2026-02-27 06:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_ticket_branch_ticket_priority_ticket_screenshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('last_issued_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('amount_before_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SmaccSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmaccSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('SALE_INVOICE', 'Sale Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('CREDITOR', 'Creditor')], max_length=30)),
                ('object_id', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('smacc_job_id', models.CharField(blank=True, default='', max_length=100)),
                ('smacc_document_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('last_error', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmaccToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], db_index=True, default='draft', max_length=20)),
                ('invoice_number', models.PositiveIntegerField()),
                ('invoice_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('issue_time', models.TimeField(default=django.utils.timezone.localtime)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer')], default='cash', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_vat_number', models.CharField(blank=True, default='', max_length=50)),
                ('subtotal_before_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('total_in_words_ar', models.TextField(blank=True, default='')),
                ('qr_payload', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField()),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('part_number', models.CharField(blank=True, default='', max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='PCS', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_before_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('warehouse_location', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'ordering': ['serial_no'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='commercial_registration_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone_primary',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone_secondary',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='branch',
            name='vat_registration_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('tech', 'Tech')], default='cashier', max_length=20),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name'], name='inventory_p_name_c0a8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_13e3f6_idx'),
        ),
        migrations.AddField(
            model_name='branchinvoicesequence',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequence', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='smaccsyncqueue',
            index=models.Index(fields=['status', 'updated_at'], name='inventory_s_status_2cc93c_idx'),
        ),
        migrations.AddIndex(
            model_name='smaccsyncqueue',
            index=models.Index(fields=['object_type', 'object_id'], name='inventory_s_object__70ec7c_idx'),
        ),
        migrations.AddIndex(
            model_name='smaccsyncqueue',
            index=models.Index(fields=['created_at'], name='inventory_s_created_fef41d_idx'),
        ),
        migrations.AddField(
            model_name='smaccsynclog',
            name='queue_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.smaccsyncqueue'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='inventory.taxinvoice'),
        ),
        migrations.AddField(
            model_name='taxinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.taxinvoice'),
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['branch', 'issue_date'], name='inventory_t_branch__94d137_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['state', 'created_at'], name='inventory_t_state_1ef3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['invoice_uuid'], name='inventory_t_invoice_423b2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxinvoice',
            constraint=models.UniqueConstraint(fields=('branch', 'invoice_number'), name='invoice_branch_number_unique'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['branch', 'created_at'], name='inventory_c_branch__2d5e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoiceline',
            index=models.Index(fields=['invoice', 'serial_no'], name='inventory_t_invoice_4f62ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxinvoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'serial_no'), name='invoice_line_serial_unique'),
        ),
    ]
