# Generated by Django 5.2.10 on 2026-02-28 02:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_branchinvoicesequence_creditnote_smaccsynclog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('return_to_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('refund', 'Refund'), ('credit_note', 'Credit Note')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_qty', models.IntegerField(default=0)),
                ('system_qty_snapshot', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CycleCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartBranchCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('last_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('credit', 'Credit')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial_received', 'Partial Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qty_received', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], db_index=True, default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('batch_lot', models.CharField(blank=True, default='', max_length=80)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('vat_number', models.CharField(blank=True, default='', max_length=50)),
                ('cr_number', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name_ar', 'name_en'],
            },
        ),
        migrations.AddField(
            model_name='creditnote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='return_to_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='state',
            field=models.CharField(db_index=True, default='posted', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='part',
            name='sku',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['customer', 'created_at'], name='inventory_c_custome_cd4ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['sku'], name='inventory_p_sku_96e24a_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['manufacturer_part_number'], name='inventory_p_manufac_86e0c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferrequest',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='transfer_received_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='transferrequest',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('quantity'))), name='transfer_received_qty_lte_qty'),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.creditnote'),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_lines', to='inventory.part'),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_lines', to='inventory.sale'),
        ),
        migrations.AddField(
            model_name='customerledgerentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerledgerentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='customerledgerentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='inventory.part'),
        ),
        migrations.AddField(
            model_name='cyclecountsession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_sessions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cyclecountsession',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_sessions', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='cyclecountsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_sessions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cyclecountsession',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_sessions', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.cyclecountsession'),
        ),
        migrations.AddField(
            model_name='partbarcode',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='inventory.part'),
        ),
        migrations.AddField(
            model_name='partbranchcost',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_costs', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='partbranchcost',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_costs', to='inventory.part'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='inventory.part'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipt_lines', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inventory.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchasereceipt'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active', 'name_ar'], name='inventory_v_is_acti_77e461_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_code'], name='inventory_v_vendor__1da05d_idx'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.vendor'),
        ),
        migrations.AddIndex(
            model_name='creditnoteline',
            index=models.Index(fields=['credit_note', 'part'], name='inventory_c_credit__6674ba_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['customer', 'created_at'], name='inventory_c_custome_6d5aea_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['entry_type', 'created_at'], name='inventory_c_entry_t_dd81a5_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountsession',
            index=models.Index(fields=['branch', 'status', 'started_at'], name='inventory_c_branch__bc5748_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountline',
            index=models.Index(fields=['session', 'part'], name='inventory_c_session_95a83e_idx'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountline',
            constraint=models.UniqueConstraint(fields=('session', 'part'), name='cycle_count_line_unique_part_per_session'),
        ),
        migrations.AddIndex(
            model_name='partbarcode',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_683ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='partbarcode',
            index=models.Index(fields=['part', 'created_at'], name='inventory_p_part_id_932f85_idx'),
        ),
        migrations.AddIndex(
            model_name='partbranchcost',
            index=models.Index(fields=['branch', 'part'], name='inventory_p_branch__73c809_idx'),
        ),
        migrations.AddConstraint(
            model_name='partbranchcost',
            constraint=models.UniqueConstraint(fields=('part', 'branch'), name='partbranchcost_part_branch_unique'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'created_at'], name='inventory_p_custome_080a54_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch', 'created_at'], name='inventory_p_branch__dbac2e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['po', 'part'], name='inventory_p_po_id_8299ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('po', 'part'), name='po_line_unique_part_per_po'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_received__gte', 0)), name='po_line_qty_received_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_received__lte', models.F('qty_ordered'))), name='po_line_qty_received_lte_ordered'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['branch', 'status', 'received_at'], name='inventory_p_branch__eed8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['po', 'received_at'], name='inventory_p_po_id_4b12ab_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptline',
            index=models.Index(fields=['receipt', 'po_line'], name='inventory_p_receipt_7027c4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptline',
            index=models.Index(fields=['location'], name='inventory_p_locatio_4a7a14_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['branch', 'status', 'created_at'], name='inventory_p_branch__51d1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor', 'created_at'], name='inventory_p_vendor__936b57_idx'),
        ),
    ]
