# Generated by Django 5.2.10 on 2026-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_userprofile_phone_number_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('invoice', 'فاتورة'), ('payment', 'دفعة'), ('refund', 'استرجاع'), ('credit_note', 'إشعار دائن')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cyclecountsession',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'قيد التنفيذ'), ('submitted', 'مرفوع'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='channel',
            field=models.CharField(choices=[('email', 'البريد الإلكتروني'), ('phone', 'الجوال')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('bank', 'تحويل بنكي'), ('credit', 'آجل')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسل'), ('partial_received', 'استلام جزئي'), ('received', 'مستلم بالكامل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='smaccsyncqueue',
            name='object_type',
            field=models.CharField(choices=[('SALE_INVOICE', 'فاتورة بيع'), ('CREDIT_NOTE', 'إشعار دائن'), ('CREDITOR', 'دائن')], max_length=30),
        ),
        migrations.AlterField(
            model_name='smaccsyncqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار المعالجة'), ('PROCESSING', 'قيد المعالجة'), ('SYNCED', 'تمت المزامنة'), ('FAILED', 'فشل')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('transfer', 'تحويل')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='state',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّلة')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'مرتفعة')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'جديدة'), ('open', 'مفتوحة'), ('in_progress', 'قيد المعالجة'), ('fixed', 'تم الإصلاح')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'مطلوب'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('picked_up', 'تم التحميل'), ('delivered', 'تم التسليم'), ('received', 'تم الاستلام')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير'), ('cashier', 'كاشير'), ('tech', 'فني')], default='cashier', max_length=20),
        ),
    ]
